model-file-names:
  etalon: src\main\resources\gmodels\EIGEN-6C4.gfc
  compared: src\main\resources\gmodels\XGM2019e_2159.gfc
  spectralAmplitudes: src\main\resources\gmodels\spectralAmplitudes2190.txt